// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA708otGqdz9gTYcAfmtA76f9wj46wl098',
    appId: '1:624114144941:web:fca36dd020b12af35a9824',
    messagingSenderId: '624114144941',
    projectId: 'flutter-chat-app-c046c',
    authDomain: 'flutter-chat-app-c046c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c046c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmvnmFdeFjbGgdFa03sC-GsQ7XCP7pw6Y',
    appId: '1:624114144941:android:ca954a5ed50eb2585a9824',
    messagingSenderId: '624114144941',
    projectId: 'flutter-chat-app-c046c',
    storageBucket: 'flutter-chat-app-c046c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyh9rEe5Mcxnn4xsHiQAhT0AYf1bREMVw',
    appId: '1:624114144941:ios:77b676dd092056b55a9824',
    messagingSenderId: '624114144941',
    projectId: 'flutter-chat-app-c046c',
    storageBucket: 'flutter-chat-app-c046c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyh9rEe5Mcxnn4xsHiQAhT0AYf1bREMVw',
    appId: '1:624114144941:ios:fdee285ae734df435a9824',
    messagingSenderId: '624114144941',
    projectId: 'flutter-chat-app-c046c',
    storageBucket: 'flutter-chat-app-c046c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
